language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
notifications:
  irc: "irc.freenode.org#adhearsion"
